import type { ModelEntry } from '../types/models';

export const MODEL_REGISTRY: ModelEntry[] = [
  // ── OpenAI ──
  {
    id: 'gpt-4.1-2025-04-14',
    providerId: 'openai',
    displayName: 'GPT-4.1',
    family: 'GPT',
    contextWindow: 1047576,
    maxOutputTokens: 32768,
    pricing: { inputPerMillionTokens: 2, outputPerMillionTokens: 8 },
    modalities: { input: ['text', 'image'], output: ['text'] },
    capabilities: {
      supportsStreaming: true, supportsThinking: false, supportsToolUse: true,
      supportsVision: true, supportsFunctionCalling: true, supportsSystemPrompt: true,
      supportsWebSearch: false, supportsJsonMode: true, supportsStructuredOutput: true,
      supportsSeed: true, supportsCaching: false, supportsTopK: false, supportsMinP: false,
      supportsFrequencyPenalty: true, supportsPresencePenalty: true, supportsRepetitionPenalty: false,
    },
    browserDirectSupported: true, transportMode: 'sse', deprecated: false,
    releaseDate: '2025-04-14', defaultSafeParams: { temperature: 1, topP: 1 },
  },
  {
    id: 'gpt-4.1-mini-2025-04-14',
    providerId: 'openai',
    displayName: 'GPT-4.1 Mini',
    family: 'GPT',
    contextWindow: 1047576,
    maxOutputTokens: 32768,
    pricing: { inputPerMillionTokens: 0.4, outputPerMillionTokens: 1.6 },
    modalities: { input: ['text', 'image'], output: ['text'] },
    capabilities: {
      supportsStreaming: true, supportsThinking: false, supportsToolUse: true,
      supportsVision: true, supportsFunctionCalling: true, supportsSystemPrompt: true,
      supportsWebSearch: false, supportsJsonMode: true, supportsStructuredOutput: true,
      supportsSeed: true, supportsCaching: false, supportsTopK: false, supportsMinP: false,
      supportsFrequencyPenalty: true, supportsPresencePenalty: true, supportsRepetitionPenalty: false,
    },
    browserDirectSupported: true, transportMode: 'sse', deprecated: false,
    releaseDate: '2025-04-14', defaultSafeParams: { temperature: 1, topP: 1 },
  },
  {
    id: 'gpt-4.1-nano-2025-04-14',
    providerId: 'openai',
    displayName: 'GPT-4.1 Nano',
    family: 'GPT',
    contextWindow: 1047576,
    maxOutputTokens: 32768,
    pricing: { inputPerMillionTokens: 0.1, outputPerMillionTokens: 0.4 },
    modalities: { input: ['text', 'image'], output: ['text'] },
    capabilities: {
      supportsStreaming: true, supportsThinking: false, supportsToolUse: true,
      supportsVision: true, supportsFunctionCalling: true, supportsSystemPrompt: true,
      supportsWebSearch: false, supportsJsonMode: true, supportsStructuredOutput: true,
      supportsSeed: true, supportsCaching: false, supportsTopK: false, supportsMinP: false,
      supportsFrequencyPenalty: true, supportsPresencePenalty: true, supportsRepetitionPenalty: false,
    },
    browserDirectSupported: true, transportMode: 'sse', deprecated: false,
    releaseDate: '2025-04-14', defaultSafeParams: { temperature: 1, topP: 1 },
  },
  {
    id: 'o3-2025-04-16',
    providerId: 'openai',
    displayName: 'o3',
    family: 'o-series',
    contextWindow: 200000,
    maxOutputTokens: 100000,
    pricing: { inputPerMillionTokens: 10, outputPerMillionTokens: 40, thinkingPerMillionTokens: 40 },
    modalities: { input: ['text', 'image'], output: ['text'] },
    capabilities: {
      supportsStreaming: true, supportsThinking: true, supportsToolUse: true,
      supportsVision: true, supportsFunctionCalling: true, supportsSystemPrompt: true,
      supportsWebSearch: false, supportsJsonMode: true, supportsStructuredOutput: true,
      supportsSeed: false, supportsCaching: false, supportsTopK: false, supportsMinP: false,
      supportsFrequencyPenalty: false, supportsPresencePenalty: false, supportsRepetitionPenalty: false,
    },
    thinkingConfig: { parameterName: 'reasoning_effort', levels: { low: 'low', medium: 'medium', high: 'high' } },
    browserDirectSupported: true, transportMode: 'sse', deprecated: false,
    releaseDate: '2025-04-16', defaultSafeParams: {},
  },
  {
    id: 'o3-pro',
    providerId: 'openai',
    displayName: 'o3 Pro',
    family: 'o-series',
    contextWindow: 200000,
    maxOutputTokens: 100000,
    pricing: { inputPerMillionTokens: 20, outputPerMillionTokens: 80, thinkingPerMillionTokens: 80 },
    modalities: { input: ['text', 'image'], output: ['text'] },
    capabilities: {
      supportsStreaming: true, supportsThinking: true, supportsToolUse: true,
      supportsVision: true, supportsFunctionCalling: true, supportsSystemPrompt: true,
      supportsWebSearch: false, supportsJsonMode: true, supportsStructuredOutput: true,
      supportsSeed: false, supportsCaching: false, supportsTopK: false, supportsMinP: false,
      supportsFrequencyPenalty: false, supportsPresencePenalty: false, supportsRepetitionPenalty: false,
    },
    thinkingConfig: { parameterName: 'reasoning_effort', levels: { low: 'low', medium: 'medium', high: 'high' } },
    browserDirectSupported: true, transportMode: 'sse', deprecated: false,
    releaseDate: '2025-06-10', defaultSafeParams: {},
  },
  {
    id: 'o4-mini',
    providerId: 'openai',
    displayName: 'o4 Mini',
    family: 'o-series',
    contextWindow: 200000,
    maxOutputTokens: 100000,
    pricing: { inputPerMillionTokens: 1.1, outputPerMillionTokens: 4.4, thinkingPerMillionTokens: 4.4 },
    modalities: { input: ['text', 'image'], output: ['text'] },
    capabilities: {
      supportsStreaming: true, supportsThinking: true, supportsToolUse: true,
      supportsVision: true, supportsFunctionCalling: true, supportsSystemPrompt: true,
      supportsWebSearch: false, supportsJsonMode: true, supportsStructuredOutput: true,
      supportsSeed: false, supportsCaching: false, supportsTopK: false, supportsMinP: false,
      supportsFrequencyPenalty: false, supportsPresencePenalty: false, supportsRepetitionPenalty: false,
    },
    thinkingConfig: { parameterName: 'reasoning_effort', levels: { low: 'low', medium: 'medium', high: 'high' } },
    browserDirectSupported: true, transportMode: 'sse', deprecated: false,
    releaseDate: '2025-04-16', defaultSafeParams: {},
  },

  // ── Anthropic ──
  {
    id: 'claude-opus-4-20250514',
    providerId: 'anthropic',
    displayName: 'Claude Opus 4',
    family: 'Claude',
    contextWindow: 200000,
    maxOutputTokens: 32768,
    pricing: { inputPerMillionTokens: 15, outputPerMillionTokens: 75, cachedInputPerMillionTokens: 1.5, thinkingPerMillionTokens: 75 },
    modalities: { input: ['text', 'image', 'file'], output: ['text'] },
    capabilities: {
      supportsStreaming: true, supportsThinking: true, supportsToolUse: true,
      supportsVision: true, supportsFunctionCalling: true, supportsSystemPrompt: true,
      supportsWebSearch: true, supportsJsonMode: false, supportsStructuredOutput: false,
      supportsSeed: false, supportsCaching: true, supportsTopK: true, supportsMinP: false,
      supportsFrequencyPenalty: false, supportsPresencePenalty: false, supportsRepetitionPenalty: false,
    },
    thinkingConfig: { parameterName: 'budget_tokens', levels: { low: 4096, medium: 16384, high: 65536 }, minBudgetTokens: 1024, maxBudgetTokens: 131072 },
    cachingConfig: { headerKey: 'cache_control', strategy: 'ephemeral' },
    browserDirectSupported: true, transportMode: 'sse', deprecated: false,
    releaseDate: '2025-05-14', defaultSafeParams: { temperature: 1 },
  },
  {
    id: 'claude-sonnet-4-20250514',
    providerId: 'anthropic',
    displayName: 'Claude Sonnet 4',
    family: 'Claude',
    contextWindow: 200000,
    maxOutputTokens: 16384,
    pricing: { inputPerMillionTokens: 3, outputPerMillionTokens: 15, cachedInputPerMillionTokens: 0.3, thinkingPerMillionTokens: 15 },
    modalities: { input: ['text', 'image', 'file'], output: ['text'] },
    capabilities: {
      supportsStreaming: true, supportsThinking: true, supportsToolUse: true,
      supportsVision: true, supportsFunctionCalling: true, supportsSystemPrompt: true,
      supportsWebSearch: true, supportsJsonMode: false, supportsStructuredOutput: false,
      supportsSeed: false, supportsCaching: true, supportsTopK: true, supportsMinP: false,
      supportsFrequencyPenalty: false, supportsPresencePenalty: false, supportsRepetitionPenalty: false,
    },
    thinkingConfig: { parameterName: 'budget_tokens', levels: { low: 2048, medium: 8192, high: 32768 }, minBudgetTokens: 1024, maxBudgetTokens: 65536 },
    cachingConfig: { headerKey: 'cache_control', strategy: 'ephemeral' },
    browserDirectSupported: true, transportMode: 'sse', deprecated: false,
    releaseDate: '2025-05-14', defaultSafeParams: { temperature: 1 },
  },
  {
    id: 'claude-haiku-4-20250514',
    providerId: 'anthropic',
    displayName: 'Claude Haiku 4',
    family: 'Claude',
    contextWindow: 200000,
    maxOutputTokens: 8192,
    pricing: { inputPerMillionTokens: 0.8, outputPerMillionTokens: 4, cachedInputPerMillionTokens: 0.08 },
    modalities: { input: ['text', 'image'], output: ['text'] },
    capabilities: {
      supportsStreaming: true, supportsThinking: false, supportsToolUse: true,
      supportsVision: true, supportsFunctionCalling: true, supportsSystemPrompt: true,
      supportsWebSearch: false, supportsJsonMode: false, supportsStructuredOutput: false,
      supportsSeed: false, supportsCaching: true, supportsTopK: true, supportsMinP: false,
      supportsFrequencyPenalty: false, supportsPresencePenalty: false, supportsRepetitionPenalty: false,
    },
    cachingConfig: { headerKey: 'cache_control', strategy: 'ephemeral' },
    browserDirectSupported: true, transportMode: 'sse', deprecated: false,
    releaseDate: '2025-05-14', defaultSafeParams: { temperature: 1 },
  },

  // ── Google ──
  {
    id: 'gemini-2.5-pro',
    providerId: 'google',
    displayName: 'Gemini 2.5 Pro',
    family: 'Gemini',
    contextWindow: 1048576,
    maxOutputTokens: 65536,
    pricing: { inputPerMillionTokens: 1.25, outputPerMillionTokens: 10, thinkingPerMillionTokens: 10 },
    modalities: { input: ['text', 'image', 'audio', 'video'], output: ['text'] },
    capabilities: {
      supportsStreaming: true, supportsThinking: true, supportsToolUse: true,
      supportsVision: true, supportsFunctionCalling: true, supportsSystemPrompt: true,
      supportsWebSearch: true, supportsJsonMode: true, supportsStructuredOutput: true,
      supportsSeed: false, supportsCaching: true, supportsTopK: true, supportsMinP: false,
      supportsFrequencyPenalty: false, supportsPresencePenalty: true, supportsRepetitionPenalty: false,
    },
    thinkingConfig: { parameterName: 'thinkingBudget', levels: { low: 2048, medium: 8192, high: 32768 } },
    browserDirectSupported: true, transportMode: 'sse', deprecated: false,
    releaseDate: '2025-03-25', defaultSafeParams: { temperature: 1 },
  },
  {
    id: 'gemini-2.5-flash',
    providerId: 'google',
    displayName: 'Gemini 2.5 Flash',
    family: 'Gemini',
    contextWindow: 1048576,
    maxOutputTokens: 65536,
    pricing: { inputPerMillionTokens: 0.15, outputPerMillionTokens: 0.6, thinkingPerMillionTokens: 0.6 },
    modalities: { input: ['text', 'image', 'audio', 'video'], output: ['text'] },
    capabilities: {
      supportsStreaming: true, supportsThinking: true, supportsToolUse: true,
      supportsVision: true, supportsFunctionCalling: true, supportsSystemPrompt: true,
      supportsWebSearch: true, supportsJsonMode: true, supportsStructuredOutput: true,
      supportsSeed: false, supportsCaching: true, supportsTopK: true, supportsMinP: false,
      supportsFrequencyPenalty: false, supportsPresencePenalty: true, supportsRepetitionPenalty: false,
    },
    thinkingConfig: { parameterName: 'thinkingBudget', levels: { low: 1024, medium: 4096, high: 16384 } },
    browserDirectSupported: true, transportMode: 'sse', deprecated: false,
    releaseDate: '2025-04-17', defaultSafeParams: { temperature: 1 },
  },
  {
    id: 'gemini-3-pro-preview',
    providerId: 'google',
    displayName: 'Gemini 3 Pro',
    family: 'Gemini',
    contextWindow: 1048576,
    maxOutputTokens: 65536,
    pricing: { inputPerMillionTokens: 2.5, outputPerMillionTokens: 15, thinkingPerMillionTokens: 15 },
    modalities: { input: ['text', 'image', 'audio', 'video'], output: ['text'] },
    capabilities: {
      supportsStreaming: true, supportsThinking: true, supportsToolUse: true,
      supportsVision: true, supportsFunctionCalling: true, supportsSystemPrompt: true,
      supportsWebSearch: true, supportsJsonMode: true, supportsStructuredOutput: true,
      supportsSeed: false, supportsCaching: true, supportsTopK: true, supportsMinP: false,
      supportsFrequencyPenalty: false, supportsPresencePenalty: true, supportsRepetitionPenalty: false,
    },
    thinkingConfig: { parameterName: 'thinkingBudget', levels: { low: 4096, medium: 16384, high: 65536 } },
    browserDirectSupported: true, transportMode: 'sse', deprecated: false,
    releaseDate: '2025-09-01', defaultSafeParams: { temperature: 1 },
  },
  {
    id: 'gemini-3-flash-preview',
    providerId: 'google',
    displayName: 'Gemini 3 Flash',
    family: 'Gemini',
    contextWindow: 1048576,
    maxOutputTokens: 65536,
    pricing: { inputPerMillionTokens: 0.15, outputPerMillionTokens: 0.6, thinkingPerMillionTokens: 0.6 },
    modalities: { input: ['text', 'image', 'audio', 'video'], output: ['text'] },
    capabilities: {
      supportsStreaming: true, supportsThinking: true, supportsToolUse: true,
      supportsVision: true, supportsFunctionCalling: true, supportsSystemPrompt: true,
      supportsWebSearch: true, supportsJsonMode: true, supportsStructuredOutput: true,
      supportsSeed: false, supportsCaching: true, supportsTopK: true, supportsMinP: false,
      supportsFrequencyPenalty: false, supportsPresencePenalty: true, supportsRepetitionPenalty: false,
    },
    thinkingConfig: { parameterName: 'thinkingBudget', levels: { low: 1024, medium: 4096, high: 16384 } },
    browserDirectSupported: true, transportMode: 'sse', deprecated: false,
    releaseDate: '2025-09-01', defaultSafeParams: { temperature: 1 },
  },
  {
    id: 'gemini-2.0-flash',
    providerId: 'google',
    displayName: 'Gemini 2.0 Flash',
    family: 'Gemini',
    contextWindow: 1048576,
    maxOutputTokens: 8192,
    pricing: { inputPerMillionTokens: 0.1, outputPerMillionTokens: 0.4 },
    modalities: { input: ['text', 'image', 'audio', 'video'], output: ['text', 'image'] },
    capabilities: {
      supportsStreaming: true, supportsThinking: false, supportsToolUse: true,
      supportsVision: true, supportsFunctionCalling: true, supportsSystemPrompt: true,
      supportsWebSearch: true, supportsJsonMode: true, supportsStructuredOutput: true,
      supportsSeed: false, supportsCaching: false, supportsTopK: true, supportsMinP: false,
      supportsFrequencyPenalty: false, supportsPresencePenalty: true, supportsRepetitionPenalty: false,
    },
    browserDirectSupported: true, transportMode: 'sse', deprecated: false,
    releaseDate: '2025-02-05', defaultSafeParams: { temperature: 1 },
  },
] satisfies ModelEntry[];
