import type { ModelEntry } from '../types/models';

/** Shared capability defaults for DRY model definitions */
const BASE_CAPS = {
  supportsStreaming: true,
  supportsThinking: false,
  supportsToolUse: true,
  supportsVision: false,
  supportsFunctionCalling: true,
  supportsSystemPrompt: true,
  supportsWebSearch: false,
  supportsJsonMode: false,
  supportsStructuredOutput: false,
  supportsSeed: false,
  supportsCaching: false,
  supportsTopK: false,
  supportsMinP: false,
  supportsFrequencyPenalty: false,
  supportsPresencePenalty: false,
  supportsRepetitionPenalty: false,
} as const;

export const MODEL_REGISTRY: ModelEntry[] = [
  // ═══════════════════════════════════════════
  // ── OpenAI ──
  // ═══════════════════════════════════════════
  {
    id: 'gpt-5.4-2026-03',
    providerId: 'openai',
    displayName: 'GPT-5.4',
    family: 'GPT',
    contextWindow: 2000000,
    maxOutputTokens: 65536,
    pricing: { inputPerMillionTokens: 3, outputPerMillionTokens: 12, thinkingPerMillionTokens: 12 },
    modalities: { input: ['text', 'image'], output: ['text'] },
    capabilities: {
      ...BASE_CAPS,
      supportsThinking: true, supportsVision: true, supportsJsonMode: true, supportsStructuredOutput: true,
      supportsSeed: true, supportsFrequencyPenalty: true, supportsPresencePenalty: true,
    },
    thinkingConfig: { parameterName: 'reasoning_effort', levels: { low: 'low', medium: 'medium', high: 'high', 'x-high': 'x-high' } },
    browserDirectSupported: true, transportMode: 'sse', deprecated: false,
    releaseDate: '2026-03-01', defaultSafeParams: { temperature: 1, topP: 1 },
  },
  {
    id: 'gpt-5.3-codex-2026-02',
    providerId: 'openai',
    displayName: 'GPT-5.3 Codex',
    family: 'GPT',
    contextWindow: 1500000,
    maxOutputTokens: 65536,
    pricing: { inputPerMillionTokens: 2.5, outputPerMillionTokens: 10, thinkingPerMillionTokens: 10 },
    modalities: { input: ['text', 'image'], output: ['text'] },
    capabilities: {
      ...BASE_CAPS,
      supportsThinking: true, supportsVision: true, supportsJsonMode: true, supportsStructuredOutput: true,
      supportsSeed: true, supportsFrequencyPenalty: true, supportsPresencePenalty: true,
    },
    thinkingConfig: { parameterName: 'reasoning_effort', levels: { low: 'low', medium: 'medium', high: 'high', 'x-high': 'x-high' } },
    browserDirectSupported: true, transportMode: 'sse', deprecated: false,
    releaseDate: '2026-02-15', defaultSafeParams: { temperature: 0.3, topP: 1 },
  },
  {
    id: 'gpt-5.3-chat-2026-02',
    providerId: 'openai',
    displayName: 'GPT-5.3 Chat',
    family: 'GPT',
    contextWindow: 1500000,
    maxOutputTokens: 65536,
    pricing: { inputPerMillionTokens: 2, outputPerMillionTokens: 8 },
    modalities: { input: ['text', 'image'], output: ['text'] },
    capabilities: {
      ...BASE_CAPS,
      supportsVision: true, supportsJsonMode: true, supportsStructuredOutput: true,
      supportsSeed: true, supportsFrequencyPenalty: true, supportsPresencePenalty: true,
    },
    browserDirectSupported: true, transportMode: 'sse', deprecated: false,
    releaseDate: '2026-02-10', defaultSafeParams: { temperature: 1, topP: 1 },
  },
  {
    id: 'gpt-4.1-2025-04-14',
    providerId: 'openai',
    displayName: 'GPT-4.1',
    family: 'GPT',
    contextWindow: 1047576,
    maxOutputTokens: 32768,
    pricing: { inputPerMillionTokens: 2, outputPerMillionTokens: 8 },
    modalities: { input: ['text', 'image'], output: ['text'] },
    capabilities: {
      ...BASE_CAPS,
      supportsVision: true, supportsJsonMode: true, supportsStructuredOutput: true,
      supportsSeed: true, supportsFrequencyPenalty: true, supportsPresencePenalty: true,
    },
    browserDirectSupported: true, transportMode: 'sse', deprecated: false, isLegacy: true,
    releaseDate: '2025-04-14', defaultSafeParams: { temperature: 1, topP: 1 },
  },
  {
    id: 'gpt-4.1-mini-2025-04-14',
    providerId: 'openai',
    displayName: 'GPT-4.1 Mini',
    family: 'GPT',
    contextWindow: 1047576,
    maxOutputTokens: 32768,
    pricing: { inputPerMillionTokens: 0.4, outputPerMillionTokens: 1.6 },
    modalities: { input: ['text', 'image'], output: ['text'] },
    capabilities: {
      ...BASE_CAPS,
      supportsVision: true, supportsJsonMode: true, supportsStructuredOutput: true,
      supportsSeed: true, supportsFrequencyPenalty: true, supportsPresencePenalty: true,
    },
    browserDirectSupported: true, transportMode: 'sse', deprecated: false, isLegacy: true,
    releaseDate: '2025-04-14', defaultSafeParams: { temperature: 1, topP: 1 },
  },
  {
    id: 'gpt-4.1-nano-2025-04-14',
    providerId: 'openai',
    displayName: 'GPT-4.1 Nano',
    family: 'GPT',
    contextWindow: 1047576,
    maxOutputTokens: 32768,
    pricing: { inputPerMillionTokens: 0.1, outputPerMillionTokens: 0.4 },
    modalities: { input: ['text', 'image'], output: ['text'] },
    capabilities: {
      ...BASE_CAPS,
      supportsVision: true, supportsJsonMode: true, supportsStructuredOutput: true,
      supportsSeed: true, supportsFrequencyPenalty: true, supportsPresencePenalty: true,
    },
    browserDirectSupported: true, transportMode: 'sse', deprecated: false, isLegacy: true,
    releaseDate: '2025-04-14', defaultSafeParams: { temperature: 1, topP: 1 },
  },
  {
    id: 'o3-2025-04-16',
    providerId: 'openai',
    displayName: 'o3',
    family: 'o-series',
    contextWindow: 200000,
    maxOutputTokens: 100000,
    pricing: { inputPerMillionTokens: 10, outputPerMillionTokens: 40, thinkingPerMillionTokens: 40 },
    modalities: { input: ['text', 'image'], output: ['text'] },
    capabilities: {
      ...BASE_CAPS,
      supportsThinking: true, supportsVision: true,
      supportsJsonMode: true, supportsStructuredOutput: true,
    },
    thinkingConfig: { parameterName: 'reasoning_effort', levels: { low: 'low', medium: 'medium', high: 'high' } },
    browserDirectSupported: true, transportMode: 'sse', deprecated: false, isLegacy: true,
    releaseDate: '2025-04-16', defaultSafeParams: {},
  },
  {
    id: 'o3-pro',
    providerId: 'openai',
    displayName: 'o3 Pro',
    family: 'o-series',
    contextWindow: 200000,
    maxOutputTokens: 100000,
    pricing: { inputPerMillionTokens: 20, outputPerMillionTokens: 80, thinkingPerMillionTokens: 80 },
    modalities: { input: ['text', 'image'], output: ['text'] },
    capabilities: {
      ...BASE_CAPS,
      supportsThinking: true, supportsVision: true,
      supportsJsonMode: true, supportsStructuredOutput: true,
    },
    thinkingConfig: { parameterName: 'reasoning_effort', levels: { low: 'low', medium: 'medium', high: 'high' } },
    browserDirectSupported: true, transportMode: 'sse', deprecated: false, isLegacy: true,
    releaseDate: '2025-06-10', defaultSafeParams: {},
  },
  {
    id: 'o4-mini',
    providerId: 'openai',
    displayName: 'o4 Mini',
    family: 'o-series',
    contextWindow: 200000,
    maxOutputTokens: 100000,
    pricing: { inputPerMillionTokens: 1.1, outputPerMillionTokens: 4.4, thinkingPerMillionTokens: 4.4 },
    modalities: { input: ['text', 'image'], output: ['text'] },
    capabilities: {
      ...BASE_CAPS,
      supportsThinking: true, supportsVision: true,
      supportsJsonMode: true, supportsStructuredOutput: true,
    },
    thinkingConfig: { parameterName: 'reasoning_effort', levels: { low: 'low', medium: 'medium', high: 'high' } },
    browserDirectSupported: true, transportMode: 'sse', deprecated: false, isLegacy: true,
    releaseDate: '2025-04-16', defaultSafeParams: {},
  },

  // ═══════════════════════════════════════════
  // ── Anthropic ──
  // ═══════════════════════════════════════════
  {
    id: 'claude-opus-4-6',
    providerId: 'anthropic',
    displayName: 'Claude Opus 4.6',
    family: 'Claude',
    contextWindow: 200000,
    maxOutputTokens: 32768,
    pricing: { inputPerMillionTokens: 15, outputPerMillionTokens: 75, cachedInputPerMillionTokens: 1.5, thinkingPerMillionTokens: 75 },
    modalities: { input: ['text', 'image', 'file'], output: ['text'] },
    capabilities: {
      ...BASE_CAPS,
      supportsThinking: true, supportsVision: true,
      supportsWebSearch: true, supportsCaching: true, supportsTopK: true,
    },
    thinkingConfig: { parameterName: 'budget_tokens', levels: { low: 4096, medium: 16384, high: 65536, 'x-high': 131072 }, minBudgetTokens: 1024, maxBudgetTokens: 131072 },
    cachingConfig: { headerKey: 'cache_control', strategy: 'ephemeral' },
    browserDirectSupported: true, transportMode: 'sse', deprecated: false,
    releaseDate: '2026-03-01', defaultSafeParams: { temperature: 1 },
  },
  {
    id: 'claude-sonnet-4-6-20260301',
    providerId: 'anthropic',
    displayName: 'Claude Sonnet 4.6',
    family: 'Claude',
    contextWindow: 200000,
    maxOutputTokens: 16384,
    pricing: { inputPerMillionTokens: 3, outputPerMillionTokens: 15, cachedInputPerMillionTokens: 0.3, thinkingPerMillionTokens: 15 },
    modalities: { input: ['text', 'image', 'file'], output: ['text'] },
    capabilities: {
      ...BASE_CAPS,
      supportsThinking: true, supportsVision: true,
      supportsWebSearch: true, supportsCaching: true, supportsTopK: true,
    },
    thinkingConfig: { parameterName: 'budget_tokens', levels: { low: 2048, medium: 8192, high: 32768, 'x-high': 65536 }, minBudgetTokens: 1024, maxBudgetTokens: 65536 },
    cachingConfig: { headerKey: 'cache_control', strategy: 'ephemeral' },
    browserDirectSupported: true, transportMode: 'sse', deprecated: false,
    releaseDate: '2026-03-01', defaultSafeParams: { temperature: 1 },
  },
  {
    id: 'claude-haiku-4-5',
    providerId: 'anthropic',
    displayName: 'Claude Haiku 4.6',
    family: 'Claude',
    contextWindow: 200000,
    maxOutputTokens: 8192,
    pricing: { inputPerMillionTokens: 0.8, outputPerMillionTokens: 4, cachedInputPerMillionTokens: 0.08 },
    modalities: { input: ['text', 'image'], output: ['text'] },
    capabilities: {
      ...BASE_CAPS,
      supportsVision: true, supportsCaching: true, supportsTopK: true,
    },
    cachingConfig: { headerKey: 'cache_control', strategy: 'ephemeral' },
    browserDirectSupported: true, transportMode: 'sse', deprecated: false,
    releaseDate: '2026-03-01', defaultSafeParams: { temperature: 1 },
  },

  // ═══════════════════════════════════════════
  // ── Google ──
  // ═══════════════════════════════════════════
  {
    id: 'gemini-3.1-pro-preview',
    providerId: 'google',
    displayName: 'Gemini 3.1 Pro',
    family: 'Gemini',
    contextWindow: 2097152,
    maxOutputTokens: 65536,
    pricing: { inputPerMillionTokens: 2.5, outputPerMillionTokens: 15, thinkingPerMillionTokens: 15 },
    modalities: { input: ['text', 'image', 'audio', 'video'], output: ['text'] },
    capabilities: {
      ...BASE_CAPS,
      supportsThinking: true, supportsVision: true,
      supportsWebSearch: true, supportsJsonMode: true, supportsStructuredOutput: true,
      supportsCaching: true, supportsTopK: true, supportsPresencePenalty: true,
    },
    thinkingConfig: { parameterName: 'thinkingBudget', levels: { low: 4096, medium: 16384, high: 65536 } },
    browserDirectSupported: true, transportMode: 'sse', deprecated: false,
    releaseDate: '2026-02-20', defaultSafeParams: { temperature: 1 },
  },
  {
    id: 'gemini-3-pro-preview',
    providerId: 'google',
    displayName: 'Gemini 3 Pro',
    family: 'Gemini',
    contextWindow: 2097152,
    maxOutputTokens: 65536,
    pricing: { inputPerMillionTokens: 2.0, outputPerMillionTokens: 12, thinkingPerMillionTokens: 12 },
    modalities: { input: ['text', 'image', 'audio', 'video'], output: ['text'] },
    capabilities: {
      ...BASE_CAPS,
      supportsThinking: true, supportsVision: true,
      supportsWebSearch: true, supportsJsonMode: true, supportsStructuredOutput: true,
      supportsCaching: true, supportsTopK: true, supportsPresencePenalty: true,
    },
    thinkingConfig: { parameterName: 'thinkingBudget', levels: { low: 4096, medium: 16384, high: 65536 } },
    browserDirectSupported: true, transportMode: 'sse', deprecated: false,
    releaseDate: '2026-01-15', defaultSafeParams: { temperature: 1 },
  },
  {
    id: 'gemini-3-flash-preview',
    providerId: 'google',
    displayName: 'Gemini 3 Flash',
    family: 'Gemini',
    contextWindow: 2097152,
    maxOutputTokens: 65536,
    pricing: { inputPerMillionTokens: 0.1, outputPerMillionTokens: 0.4, thinkingPerMillionTokens: 0.4 },
    modalities: { input: ['text', 'image', 'audio', 'video'], output: ['text'] },
    capabilities: {
      ...BASE_CAPS,
      supportsThinking: true, supportsVision: true,
      supportsWebSearch: true, supportsJsonMode: true, supportsStructuredOutput: true,
      supportsCaching: true, supportsTopK: true, supportsPresencePenalty: true,
    },
    thinkingConfig: { parameterName: 'thinkingBudget', levels: { low: 1024, medium: 4096, high: 16384 } },
    browserDirectSupported: true, transportMode: 'sse', deprecated: false,
    releaseDate: '2026-01-15', defaultSafeParams: { temperature: 1 },
  },
  {
    id: 'gemini-2.5-pro',
    providerId: 'google',
    displayName: 'Gemini 2.5 Pro',
    family: 'Gemini',
    contextWindow: 1048576,
    maxOutputTokens: 65536,
    pricing: { inputPerMillionTokens: 1.25, outputPerMillionTokens: 10, thinkingPerMillionTokens: 10 },
    modalities: { input: ['text', 'image', 'audio', 'video'], output: ['text'] },
    capabilities: {
      ...BASE_CAPS,
      supportsThinking: true, supportsVision: true,
      supportsWebSearch: true, supportsJsonMode: true, supportsStructuredOutput: true,
      supportsCaching: true, supportsTopK: true, supportsPresencePenalty: true,
    },
    thinkingConfig: { parameterName: 'thinkingBudget', levels: { low: 2048, medium: 8192, high: 32768 } },
    browserDirectSupported: true, transportMode: 'sse', deprecated: false, isLegacy: true,
    releaseDate: '2025-03-25', defaultSafeParams: { temperature: 1 },
  },
  {
    id: 'gemini-2.5-flash',
    providerId: 'google',
    displayName: 'Gemini 2.5 Flash',
    family: 'Gemini',
    contextWindow: 1048576,
    maxOutputTokens: 65536,
    pricing: { inputPerMillionTokens: 0.15, outputPerMillionTokens: 0.6, thinkingPerMillionTokens: 0.6 },
    modalities: { input: ['text', 'image', 'audio', 'video'], output: ['text'] },
    capabilities: {
      ...BASE_CAPS,
      supportsThinking: true, supportsVision: true,
      supportsWebSearch: true, supportsJsonMode: true, supportsStructuredOutput: true,
      supportsCaching: true, supportsTopK: true, supportsPresencePenalty: true,
    },
    thinkingConfig: { parameterName: 'thinkingBudget', levels: { low: 1024, medium: 4096, high: 16384 } },
    browserDirectSupported: true, transportMode: 'sse', deprecated: false, isLegacy: true,
    releaseDate: '2025-04-17', defaultSafeParams: { temperature: 1 },
  },
  {
    id: 'gemini-2.0-flash',
    providerId: 'google',
    displayName: 'Gemini 2.0 Flash',
    family: 'Gemini',
    contextWindow: 1048576,
    maxOutputTokens: 8192,
    pricing: { inputPerMillionTokens: 0.1, outputPerMillionTokens: 0.4 },
    modalities: { input: ['text', 'image', 'audio', 'video'], output: ['text', 'image'] },
    capabilities: {
      ...BASE_CAPS,
      supportsVision: true,
      supportsWebSearch: true, supportsJsonMode: true, supportsStructuredOutput: true,
      supportsTopK: true, supportsPresencePenalty: true,
    },
    browserDirectSupported: true, transportMode: 'sse', deprecated: false, isLegacy: true,
    releaseDate: '2025-02-05', defaultSafeParams: { temperature: 1 },
  },

  // ═══════════════════════════════════════════
  // ── Mistral ──
  // ═══════════════════════════════════════════
  {
    id: 'mistral-large-latest',
    providerId: 'mistral',
    displayName: 'Mistral Large',
    family: 'Mistral',
    contextWindow: 131072,
    maxOutputTokens: 8192,
    pricing: { inputPerMillionTokens: 2, outputPerMillionTokens: 6 },
    modalities: { input: ['text', 'image'], output: ['text'] },
    capabilities: {
      ...BASE_CAPS,
      supportsVision: true, supportsJsonMode: true, supportsStructuredOutput: true,
      supportsFrequencyPenalty: true, supportsPresencePenalty: true, supportsSeed: true,
    },
    browserDirectSupported: true, transportMode: 'sse', deprecated: false,
    releaseDate: '2025-11-01', defaultSafeParams: { temperature: 0.7 },
  },
  {
    id: 'mistral-medium-latest',
    providerId: 'mistral',
    displayName: 'Mistral Medium',
    family: 'Mistral',
    contextWindow: 131072,
    maxOutputTokens: 8192,
    pricing: { inputPerMillionTokens: 0.4, outputPerMillionTokens: 2 },
    modalities: { input: ['text', 'image'], output: ['text'] },
    capabilities: {
      ...BASE_CAPS,
      supportsVision: true, supportsJsonMode: true,
      supportsFrequencyPenalty: true, supportsPresencePenalty: true, supportsSeed: true,
    },
    browserDirectSupported: true, transportMode: 'sse', deprecated: false,
    releaseDate: '2025-12-01', defaultSafeParams: { temperature: 0.7 },
  },
  {
    id: 'mistral-small-latest',
    providerId: 'mistral',
    displayName: 'Mistral Small',
    family: 'Mistral',
    contextWindow: 131072,
    maxOutputTokens: 8192,
    pricing: { inputPerMillionTokens: 0.1, outputPerMillionTokens: 0.3 },
    modalities: { input: ['text', 'image'], output: ['text'] },
    capabilities: {
      ...BASE_CAPS,
      supportsVision: true, supportsJsonMode: true,
      supportsFrequencyPenalty: true, supportsPresencePenalty: true, supportsSeed: true,
    },
    browserDirectSupported: true, transportMode: 'sse', deprecated: false,
    releaseDate: '2025-09-01', defaultSafeParams: { temperature: 0.7 },
  },
  {
    id: 'codestral-latest',
    providerId: 'mistral',
    displayName: 'Codestral',
    family: 'Mistral',
    contextWindow: 262144,
    maxOutputTokens: 8192,
    pricing: { inputPerMillionTokens: 0.3, outputPerMillionTokens: 0.9 },
    modalities: { input: ['text'], output: ['text'] },
    capabilities: {
      ...BASE_CAPS,
      supportsJsonMode: true,
      supportsFrequencyPenalty: true, supportsPresencePenalty: true, supportsSeed: true,
    },
    browserDirectSupported: true, transportMode: 'sse', deprecated: false,
    releaseDate: '2025-05-01', defaultSafeParams: { temperature: 0.3 },
  },
  {
    id: 'pixtral-large-latest',
    providerId: 'mistral',
    displayName: 'Pixtral Large',
    family: 'Mistral',
    contextWindow: 131072,
    maxOutputTokens: 8192,
    pricing: { inputPerMillionTokens: 2, outputPerMillionTokens: 6 },
    modalities: { input: ['text', 'image'], output: ['text'] },
    capabilities: {
      ...BASE_CAPS,
      supportsVision: true, supportsJsonMode: true, supportsStructuredOutput: true,
      supportsFrequencyPenalty: true, supportsPresencePenalty: true, supportsSeed: true,
    },
    browserDirectSupported: true, transportMode: 'sse', deprecated: false,
    releaseDate: '2025-02-01', defaultSafeParams: { temperature: 0.7 },
  },

  // ═══════════════════════════════════════════
  // ── Groq ──
  // ═══════════════════════════════════════════
  {
    id: 'llama-3.3-70b-versatile',
    providerId: 'groq',
    displayName: 'Llama 3.3 70B',
    family: 'Llama',
    contextWindow: 131072,
    maxOutputTokens: 32768,
    pricing: { inputPerMillionTokens: 0.59, outputPerMillionTokens: 0.79 },
    modalities: { input: ['text'], output: ['text'] },
    capabilities: {
      ...BASE_CAPS,
      supportsJsonMode: true,
      supportsFrequencyPenalty: true, supportsPresencePenalty: true, supportsSeed: true,
    },
    browserDirectSupported: true, transportMode: 'sse', deprecated: false,
    releaseDate: '2025-01-15', defaultSafeParams: { temperature: 0.7 },
  },
  {
    id: 'llama-4-scout-17b-16e-instruct',
    providerId: 'groq',
    displayName: 'Llama 4 Scout 17B',
    family: 'Llama',
    contextWindow: 131072,
    maxOutputTokens: 8192,
    pricing: { inputPerMillionTokens: 0.11, outputPerMillionTokens: 0.34 },
    modalities: { input: ['text', 'image'], output: ['text'] },
    capabilities: {
      ...BASE_CAPS,
      supportsVision: true, supportsJsonMode: true,
      supportsFrequencyPenalty: true, supportsPresencePenalty: true, supportsSeed: true,
    },
    browserDirectSupported: true, transportMode: 'sse', deprecated: false,
    releaseDate: '2025-04-05', defaultSafeParams: { temperature: 0.7 },
  },
  {
    id: 'llama-4-maverick-17b-128e-instruct',
    providerId: 'groq',
    displayName: 'Llama 4 Maverick 17B',
    family: 'Llama',
    contextWindow: 131072,
    maxOutputTokens: 8192,
    pricing: { inputPerMillionTokens: 0.20, outputPerMillionTokens: 0.60 },
    modalities: { input: ['text', 'image'], output: ['text'] },
    capabilities: {
      ...BASE_CAPS,
      supportsVision: true, supportsJsonMode: true,
      supportsFrequencyPenalty: true, supportsPresencePenalty: true, supportsSeed: true,
    },
    browserDirectSupported: true, transportMode: 'sse', deprecated: false,
    releaseDate: '2025-04-05', defaultSafeParams: { temperature: 0.7 },
  },
  {
    id: 'gemma2-9b-it',
    providerId: 'groq',
    displayName: 'Gemma 2 9B',
    family: 'Gemma',
    contextWindow: 8192,
    maxOutputTokens: 8192,
    pricing: { inputPerMillionTokens: 0.20, outputPerMillionTokens: 0.20 },
    modalities: { input: ['text'], output: ['text'] },
    capabilities: {
      ...BASE_CAPS,
      supportsJsonMode: true,
      supportsFrequencyPenalty: true, supportsPresencePenalty: true, supportsSeed: true,
    },
    browserDirectSupported: true, transportMode: 'sse', deprecated: false,
    releaseDate: '2024-08-01', defaultSafeParams: { temperature: 0.7 },
  },
  {
    id: 'deepseek-r1-distill-llama-70b',
    providerId: 'groq',
    displayName: 'DeepSeek R1 70B',
    family: 'DeepSeek',
    contextWindow: 131072,
    maxOutputTokens: 16384,
    pricing: { inputPerMillionTokens: 0.75, outputPerMillionTokens: 0.99 },
    modalities: { input: ['text'], output: ['text'] },
    capabilities: {
      ...BASE_CAPS,
      supportsThinking: true, supportsJsonMode: true,
      supportsFrequencyPenalty: true, supportsPresencePenalty: true, supportsSeed: true,
    },
    browserDirectSupported: true, transportMode: 'sse', deprecated: false,
    releaseDate: '2025-01-20', defaultSafeParams: { temperature: 0.6 },
  },

  // ═══════════════════════════════════════════
  // ── Cohere ──
  // ═══════════════════════════════════════════
  {
    id: 'command-a-03-2025',
    providerId: 'cohere',
    displayName: 'Command A',
    family: 'Command',
    contextWindow: 256000,
    maxOutputTokens: 8192,
    pricing: { inputPerMillionTokens: 2.5, outputPerMillionTokens: 10 },
    modalities: { input: ['text'], output: ['text'] },
    capabilities: {
      ...BASE_CAPS,
      supportsWebSearch: true, supportsJsonMode: true,
      supportsTopK: true, supportsFrequencyPenalty: true, supportsPresencePenalty: true, supportsSeed: true,
    },
    browserDirectSupported: true, transportMode: 'sse', deprecated: false,
    releaseDate: '2025-03-01', defaultSafeParams: { temperature: 0.3 },
  },
  {
    id: 'command-r-plus-08-2024',
    providerId: 'cohere',
    displayName: 'Command R+',
    family: 'Command',
    contextWindow: 128000,
    maxOutputTokens: 4096,
    pricing: { inputPerMillionTokens: 2.5, outputPerMillionTokens: 10 },
    modalities: { input: ['text'], output: ['text'] },
    capabilities: {
      ...BASE_CAPS,
      supportsWebSearch: true, supportsJsonMode: true,
      supportsTopK: true, supportsFrequencyPenalty: true, supportsPresencePenalty: true, supportsSeed: true,
    },
    browserDirectSupported: true, transportMode: 'sse', deprecated: false,
    releaseDate: '2024-08-01', defaultSafeParams: { temperature: 0.3 },
  },
  {
    id: 'command-r-08-2024',
    providerId: 'cohere',
    displayName: 'Command R',
    family: 'Command',
    contextWindow: 128000,
    maxOutputTokens: 4096,
    pricing: { inputPerMillionTokens: 0.15, outputPerMillionTokens: 0.6 },
    modalities: { input: ['text'], output: ['text'] },
    capabilities: {
      ...BASE_CAPS,
      supportsWebSearch: true, supportsJsonMode: true,
      supportsTopK: true, supportsFrequencyPenalty: true, supportsPresencePenalty: true, supportsSeed: true,
    },
    browserDirectSupported: true, transportMode: 'sse', deprecated: false,
    releaseDate: '2024-08-01', defaultSafeParams: { temperature: 0.3 },
  },

  // ═══════════════════════════════════════════
  // ── Together AI ──
  // ═══════════════════════════════════════════
  {
    id: 'meta-llama/Llama-4-Maverick-17B-128E-Instruct-Turbo',
    providerId: 'together',
    displayName: 'Llama 4 Maverick 17B',
    family: 'Llama',
    contextWindow: 131072,
    maxOutputTokens: 8192,
    pricing: { inputPerMillionTokens: 0.27, outputPerMillionTokens: 0.85 },
    modalities: { input: ['text', 'image'], output: ['text'] },
    capabilities: {
      ...BASE_CAPS,
      supportsVision: true, supportsJsonMode: true,
      supportsFrequencyPenalty: true, supportsPresencePenalty: true, supportsRepetitionPenalty: true,
    },
    browserDirectSupported: true, transportMode: 'sse', deprecated: false,
    releaseDate: '2025-04-05', defaultSafeParams: { temperature: 0.7 },
  },
  {
    id: 'meta-llama/Llama-4-Scout-17B-16E-Instruct',
    providerId: 'together',
    displayName: 'Llama 4 Scout 17B',
    family: 'Llama',
    contextWindow: 524288,
    maxOutputTokens: 8192,
    pricing: { inputPerMillionTokens: 0.18, outputPerMillionTokens: 0.59 },
    modalities: { input: ['text', 'image'], output: ['text'] },
    capabilities: {
      ...BASE_CAPS,
      supportsVision: true, supportsJsonMode: true,
      supportsFrequencyPenalty: true, supportsPresencePenalty: true, supportsRepetitionPenalty: true,
    },
    browserDirectSupported: true, transportMode: 'sse', deprecated: false,
    releaseDate: '2025-04-05', defaultSafeParams: { temperature: 0.7 },
  },
  {
    id: 'deepseek-ai/DeepSeek-R1',
    providerId: 'together',
    displayName: 'DeepSeek R1',
    family: 'DeepSeek',
    contextWindow: 163840,
    maxOutputTokens: 16384,
    pricing: { inputPerMillionTokens: 3.0, outputPerMillionTokens: 7.0 },
    modalities: { input: ['text'], output: ['text'] },
    capabilities: {
      ...BASE_CAPS,
      supportsThinking: true, supportsJsonMode: true,
      supportsFrequencyPenalty: true, supportsPresencePenalty: true, supportsRepetitionPenalty: true,
    },
    browserDirectSupported: true, transportMode: 'sse', deprecated: false,
    releaseDate: '2025-01-20', defaultSafeParams: { temperature: 0.6 },
  },
  {
    id: 'deepseek-ai/DeepSeek-V3',
    providerId: 'together',
    displayName: 'DeepSeek V3',
    family: 'DeepSeek',
    contextWindow: 131072,
    maxOutputTokens: 16384,
    pricing: { inputPerMillionTokens: 0.90, outputPerMillionTokens: 0.90 },
    modalities: { input: ['text'], output: ['text'] },
    capabilities: {
      ...BASE_CAPS,
      supportsJsonMode: true,
      supportsFrequencyPenalty: true, supportsPresencePenalty: true, supportsRepetitionPenalty: true,
    },
    browserDirectSupported: true, transportMode: 'sse', deprecated: false,
    releaseDate: '2025-02-01', defaultSafeParams: { temperature: 0.7 },
  },
  {
    id: 'Qwen/Qwen2.5-72B-Instruct-Turbo',
    providerId: 'together',
    displayName: 'Qwen 2.5 72B',
    family: 'Qwen',
    contextWindow: 131072,
    maxOutputTokens: 8192,
    pricing: { inputPerMillionTokens: 0.60, outputPerMillionTokens: 0.60 },
    modalities: { input: ['text'], output: ['text'] },
    capabilities: {
      ...BASE_CAPS,
      supportsJsonMode: true,
      supportsFrequencyPenalty: true, supportsPresencePenalty: true, supportsRepetitionPenalty: true,
    },
    browserDirectSupported: true, transportMode: 'sse', deprecated: false,
    releaseDate: '2024-11-01', defaultSafeParams: { temperature: 0.7 },
  },

  // ═══════════════════════════════════════════
  // ── Ollama (local) ──
  // ═══════════════════════════════════════════
  {
    id: 'llama3.3',
    providerId: 'ollama',
    displayName: 'Llama 3.3 (Local)',
    family: 'Llama',
    contextWindow: 131072,
    maxOutputTokens: 32768,
    pricing: { inputPerMillionTokens: 0, outputPerMillionTokens: 0 },
    modalities: { input: ['text'], output: ['text'] },
    capabilities: { ...BASE_CAPS, supportsJsonMode: true },
    browserDirectSupported: false, transportMode: 'sse', deprecated: false,
    releaseDate: '2025-01-01', defaultSafeParams: { temperature: 0.7 },
  },
  {
    id: 'qwen2.5:72b',
    providerId: 'ollama',
    displayName: 'Qwen 2.5 72B (Local)',
    family: 'Qwen',
    contextWindow: 131072,
    maxOutputTokens: 8192,
    pricing: { inputPerMillionTokens: 0, outputPerMillionTokens: 0 },
    modalities: { input: ['text'], output: ['text'] },
    capabilities: { ...BASE_CAPS, supportsJsonMode: true },
    browserDirectSupported: false, transportMode: 'sse', deprecated: false,
    releaseDate: '2024-11-01', defaultSafeParams: { temperature: 0.7 },
  },
  {
    id: 'deepseek-r1:70b',
    providerId: 'ollama',
    displayName: 'DeepSeek R1 70B (Local)',
    family: 'DeepSeek',
    contextWindow: 131072,
    maxOutputTokens: 16384,
    pricing: { inputPerMillionTokens: 0, outputPerMillionTokens: 0 },
    modalities: { input: ['text'], output: ['text'] },
    capabilities: { ...BASE_CAPS, supportsThinking: true, supportsJsonMode: true },
    browserDirectSupported: false, transportMode: 'sse', deprecated: false,
    releaseDate: '2025-01-20', defaultSafeParams: { temperature: 0.6 },
  },
  {
    id: 'gemma2:27b',
    providerId: 'ollama',
    displayName: 'Gemma 2 27B (Local)',
    family: 'Gemma',
    contextWindow: 8192,
    maxOutputTokens: 8192,
    pricing: { inputPerMillionTokens: 0, outputPerMillionTokens: 0 },
    modalities: { input: ['text'], output: ['text'] },
    capabilities: { ...BASE_CAPS },
    browserDirectSupported: false, transportMode: 'sse', deprecated: false,
    releaseDate: '2024-08-01', defaultSafeParams: { temperature: 0.7 },
  },
  {
    id: 'mistral:7b',
    providerId: 'ollama',
    displayName: 'Mistral 7B (Local)',
    family: 'Mistral',
    contextWindow: 32768,
    maxOutputTokens: 8192,
    pricing: { inputPerMillionTokens: 0, outputPerMillionTokens: 0 },
    modalities: { input: ['text'], output: ['text'] },
    capabilities: { ...BASE_CAPS },
    browserDirectSupported: false, transportMode: 'sse', deprecated: false,
    releaseDate: '2024-06-01', defaultSafeParams: { temperature: 0.7 },
  },
  // ═══════════════════════════════════════════
  // ── Kimi (Moonshot) — coding-specialized ──
  // ═══════════════════════════════════════════
  {
    id: 'kimi-for-coding',
    providerId: 'kimi',
    displayName: 'Kimi K2.6 Code',
    family: 'Kimi',
    contextWindow: 256000,
    maxOutputTokens: 16384,
    pricing: { inputPerMillionTokens: 0.6, outputPerMillionTokens: 2.4 },
    modalities: { input: ['text'], output: ['text'] },
    capabilities: {
      ...BASE_CAPS,
      supportsJsonMode: true,
      supportsStructuredOutput: true,
      supportsSeed: true,
      supportsFrequencyPenalty: true,
      supportsPresencePenalty: true,
    },
    browserDirectSupported: true,
    transportMode: 'sse',
    deprecated: false,
    releaseDate: '2026-04-01',
    defaultSafeParams: { temperature: 0.2, topP: 0.95 },
  },
  {
    id: 'moonshotai/kimi-k2.6',
    providerId: 'kimi',
    displayName: 'Kimi K2.6',
    family: 'Kimi',
    contextWindow: 256000,
    maxOutputTokens: 16384,
    pricing: { inputPerMillionTokens: 0.5, outputPerMillionTokens: 2 },
    modalities: { input: ['text', 'image'], output: ['text'] },
    capabilities: {
      ...BASE_CAPS,
      supportsVision: true,
      supportsJsonMode: true,
      supportsStructuredOutput: true,
      supportsSeed: true,
      supportsFrequencyPenalty: true,
      supportsPresencePenalty: true,
    },
    browserDirectSupported: true,
    transportMode: 'sse',
    deprecated: false,
    releaseDate: '2026-04-15',
    defaultSafeParams: { temperature: 0.6, topP: 0.95 },
  },
] satisfies ModelEntry[];
